name: "publish"

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and publish slides
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          npm install --global reveal-md
      - name: Build slides
        run: |
          reveal-md demo/slides.md --static public  --static-dirs=demo/.nojekyll
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public
      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
